// test
export const SAMPLE = 'SAMPLE';

// api signals for setting loading state
export const API_START = 'API_START';
export const API_END = 'API_END';

// lookups
export const SET_HONORIFICS = 'SET_HONORIFICS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_HOMEPAGE_CONTENT = 'SET_HOMEPAGE_CONTENT';
export const SET_PRESENTATION_CATEGORIES = 'SET_PRESENTATION_CATEGORIES';
export const SET_REGISTRATION_CATEGORIES = 'SET_REGISTRATION_CATEGORIES';

// auth
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const LOGOUT = 'LOGOUT';

export const SET_SIGNUP_EMAIL = 'SET_SIGNUP_EMAIL';
export const SET_CURRENT_SUBSCRIBER = 'SET_CURRENT_SUBSCRIBER';

export const GET_ADMIN = 'GET_ADMIN';
export const GET_CURRENT_SUBSCRIBER = 'GET_CURRENT_SUBSCRIBER';

// abstract
export const CREATE_ABSTRACT = 'CREATE_ABSTRACT';
export const UPDATE_ABSTRACT_CONTENT = 'UPDATE_ABSTRACT_CONTENT';
export const GET_SUBCRIBER_ABSTRACTS = 'GET_SUBCRIBER_ABSTRACTS';
export const REMOVE_ABSTRACT_COMPLETELY = 'REMOVE_ABSTRACT_COMPLETELY';

export const SET_ALL_ABSTRACTS = 'SET_ALL_ABSTRACTS';
export const UPDATE_ONE_ABSTRACT_STATUS = 'UPDATE_ONE_ABSTRACT_STATUS';
export const UPDATE_MANY_ABSTRACTS_STATUS = 'UPDATE_MANY_ABSTRACTS_STATUS';

// conference registration
export const SET_CONF_REG_STATUS = 'SET_CONF_REG_STATUS';
export const SET_USER_REGISTRATIONS = 'SET_USER_REGISTRATIONS';
