// lookup
export const GET_HOMEPAGE_CONTENT = 'GET_HOMEPAGE_CONTENT';

// conference registration
export const CREATE_CONFERENCE_REGISTRATION = 'CREATE_CONFERENCE_REGISTRATION';
export const GET_USER_REGISTRATIONS = 'GET_USER_REGISTRATIONS';
export const APPROVE_USER_PAYMENT = 'APPROVE_USER_PAYMENT';

// abstract
export const GET_ALL_ABSTRACTS = 'GET_ALL_ABSTRACTS';
export const CHANGE_ONE_ABSTRACT_STATUS = 'CHANGE_ONE_ABSTRACT_STATUS';
export const CHANGE_MANY_ABSTRACTS_STATUS = 'CHANGE_MANY_ABSTRACTS_STATUS';
